### PR TITLE
Added PlotSquared protection support

### PR DESCRIPTION
**Pull request by Redemption198**
As requested on https://github.com/TheBusyBiscuit/CS-CoreLib/issues/33

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
PlotSquared is missing from the pom.xml

**Comment by Redemption198** [comment]
@TheBusyBiscuit I can't find a way to put PlotSquared to pom.xml, I've tried with jitpack.io but nothing.
I've found their maven repo (http://ci.athion.net/) but I don't know how to put it inside the pom.xml

**Comment by TheBusyBiscuit** [comment]
Never target "latest" as the version, specify an explicit build/version

**Comment by TheBusyBiscuit** [comment]
Merged.

It also compiled successfully
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/

**Pull request merged**
