### PR TITLE
Use update(true) instead of refreshChunk

### PR DESCRIPTION
**Pull request by jiongjionger**
refreshChunk can significantly affect performance and introduce some unpredictable problems (chunk rendering errors, entities become invisible)

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Did you confirm that it still works?
I think this was done for a reason because .update() did not work correctly in older versions.

**Comment by jiongjionger** [comment]
I have been testing on my server for a few days. I am sure it works.

**Comment by jiongjionger** [comment]
update() method needs to be manually set to true to force a refresh.
update(forceRefresh, applyPhysics);

**Comment by jiongjionger** [comment]
old:
(https://s1.ax1x.com/2018/09/09/iiI3vD.gif)

new:
(https://s1.ax1x.com/2018/09/09/iiIGKe.gif)

**Pull request merged**
