### PR TITLE
Added a support for RedProtect

### PR DESCRIPTION
**Pull request by DrOreo002**
This is a support request for this[ Issue](https://github.com/TheBusyBiscuit/Slimefun4/issues/641)

### CODE REVIEW

**Comment by DrOreo002** [comment]
I had to update the version of ASkyBlock. Since that version that the plugin's using is outdated and maven cannot find that version, so prob the author of ASkyBlock removed it from the maven repo

**Comment by PutraAK** [comment]
Up

**Review by TheBusyBiscuit — APPROVED** [review]

**Comment by TheBusyBiscuit** [comment]
Compiled with no errors https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/#7

**Comment by DrOreo002** [comment]
Thanks :3

**Pull request merged**
