### PR TITLE
Updated for 1.13

### PR DESCRIPTION
**Pull request by Catzy44**
I updatedev erything to 1.13

Fixed particles,materials,setdata,etc.
Everything is working ( particles too :) )
Tested it on my mc server - endimc.pl (poland)

I created a SlimeFun pull request too.

### CODE REVIEW

**Comment by VoidAngel** [comment]
What version of worldguard are you using for this?
Ive tried compiling with the newest 1.13 dev builds of worldguard but the API seems to be different now. D:

EDIT: Actually nevermind that xD Im going to just assume that the dev builds are fragmented right now, as the WorldGuard API documentation isn't consistent with the newest builds.

**Comment by Catzy44** [comment]
Yes, latest beta version of worldguard is broken. Use 6.1.9 instead.

**Comment by Catzy44** [comment]
Latest jar files working with 1.13:
https://drive.google.com/open?id=13rSlLxNKxH_hRLXsOVNwZtqzNO3bp8DS

**Comment by rlf** [comment]
Tested this on 1.13, and couldn't get any of the CargoNet to work.

The PR doesn't respect any sort of previous coding-guideline, meaning it's impossible to see the actual changes in the diff.
image
This sort of diff is next to totally useless.
Too bad, would have loved for this to work.

**Pull request closed without merging**
